name: TestPyPI

#
# Publishes package to TestPyPI using Poetry.
#
# - Can be used safely on all types of commit references.
# - Will fail if the the version is already available on TestPyPI.
# - No tests, sanity checks, or anything like that before release.
#

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release to TestPyPI. Must follow PEP 440.
        type: string
        default: ""

env:
  poetry_version: "1.3.2"
  python_version: "3.11"

jobs:
  testpypi:
    name: TestPyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # ------------------------------------------------------------------------
      # Python & Poetry.

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}

      - name: Cache Poetry installation
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/bin/poetry
            ~/.local/share/pypoetry
          key: ${{ runner.os }}-poetry-installation-${{ env.python_version }}-${{ env.poetry_version }}-0

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -
        env:
          POETRY_VERSION: ${{ env.poetry_version }}

      # ------------------------------------------------------------------------
      # Release to TestPyPI.

      - name: Adjust package version
        if:  ${{ inputs.version != '' }}
        run: poetry version -- ${{ inputs.version }}

      - name: Configure Poetry repo for TestPyPI
        run: poetry config repositories.testpypi https://test.pypi.org/legacy/

      - name: Publish to TestPyPI with Poetry
        run: poetry publish --build -n -r testpypi -u __token__ -p "$TOKEN"
        env:
          TOKEN: ${{ secrets.TESTPYPI_TOKEN }}
